FROM apache/airflow:2.5.1
USER root

# Install OpenJDK-11
RUN apt-get update \
  && apt-get install -y --no-install-recommends openjdk-11-jre-headless \
  && apt-get autoremove -yqq --purge && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Set JAVA_HOME
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64/
RUN export JAVA_HOME

USER airflow

COPY ./requirements.txt /
RUN pip install --no-cache-dir -r /requirements.txt

COPY --chown=airflow:root ./dags /opt/airflow/dags